### ISSUE TITLE
rosedb 里 list 列表结构的设计图

### ISSUE THREAD

**Issue by yanxiaoqi932** [rfyiamcool/notes#133]
您好，rosedb 里 list 列表结构的设计图是否放错了，放的是string的图

**Comment by yanxiaoqi932** [comment]
https://github.com/rfyiamcool/notes/blob/main/rosedb_bitcask_summary.md

**Comment by rfyiamcool** [comment]
是的，已改正。😁

**Comment by rfyiamcool** [comment]
@yanxiaoqi932  再看看有啥问题？

**Comment by yanxiaoqi932** [comment]
目前没有问题了，如果有问题我再向您反馈:smile:
