### ISSUE TITLE
Flannel 采用的是 overlay 网络模式说法欠妥

### ISSUE THREAD

**Issue by lowang-bh** [rfyiamcool/notes#177]
`Flannel 采用的是 overlay 网络模式`说法不太对，hostgw 是采用underlay模式，没有封包

**Comment by rfyiamcool** [comment]
@lowang-bh 

#178

**Comment by rfyiamcool** [comment]
@lowang-bh  大佬给个联系方式，或者你加我微信 rfyiamcool
