### ISSUE TITLE
您好，有些问题想问的

### ISSUE THREAD

**Issue by googs1025** [rfyiamcool/notes#86]
您好前辈，看到您源码分析的文章，对我帮助很大！
最近我有时间也会看看源码分析，也想一起搭建您创建的这个项目～

**Comment by rfyiamcool** [comment]
啥意思？ 😅

**Comment by googs1025** [comment]
啊啊 我可能没有表达清楚。
就是这个项目是开放给大家一起能提mr的吗 ？如果我有些自己的总结也能提mr 是吗
